= Ironclad Connector Release Notes
:keywords: ironclad

The Anypoint Ironclad Connector provides the capability to connect a Mule app to retrieve information about ironclad contracts and change the schema of existing contracts.

== Ironclad Connector 1.0.0

Ironclad Connector is available on Mule 4.4 or later.


[%header%autowidth]
|===
|Application/Service |Version
|Mule Runtime	     |  4.4 or later
|Java	             |  1.8 and later
|===


==== Key Features

The Ironclad Connector supports the following operations:

* Create Record

Operation that can be used to create a contract record by specifying its intended metadata properties.

* Create Webhook

Operation that can be used to create a webhook for the specified events. Send separate requests if you need to create webhooks for multiple target URLs. Each target URL may only have one active registration.

* Create a Workflow Asynchronously

Operation that can be used to launch a new Workflow asynchronously for non-blocking performance, which is helpful when/if you provide files to the Workflow.

* List All Records

Operation that can be used to view all records in the company, with filtering available via query parameters.

* List All Workflow Approvals

Operation that returns a list of approvals for the workflow. The approvalGroups property will display only triggered approvals (i.e. conditional approvals that have not been triggered will not appear).

* List All Workflow Signers

Operation that returns a list of workflow signers and the status of their signature.

* List All Workflows

Operation that returns all workflows in your Ironclad account.

* Retrieve Record

Operation that returns a specific record and its associated data.

* Retrieve Records Schema

Operation that returns the schema associated with contract records, including available record types and metadata properties.

* Retrieve Workflow

Operation that returns the data associated with a specific workflow.

* Retrieve Workflow Schema

Operation that returns the fields used in the workflow's launch form.

* Retrieve the Sttus of an Async Workflow Create Job

Operation that can be used to check the status of a Workflow you created while using the Create a Workflow Async route.

* Update Approval on a Workflow

Operation that can be used to update an approval to the specified status. Approvals can only be updated during the Review step and when a given approval group is active (when it is that group's turn to approve).

* Update Record Metadata

Operation that can be used to update specific fields on a record.

* Update Workflow Metadata

Operation that can be used to update the metadata of a Workflow. The workflow must be in the Review step in order for its data to be updated. Use the remove action to clear field values and the set action to add or modify values. Form validation is enforced; required fields cannot be removed and any required fields triggered by conditions must be populated.

Add this dependency to your application pom.xml
```

<groupId>com.mulesoft.connectors</groupId>
<artifactId>mule4-ironclad-connector</artifactId>
<version>1.0.0</version>
<classifier>mule-plugin</classifier>

```
